### ISSUE TITLE
课后练习的编程实践参考答案

### ISSUE THREAD

**Issue by kabrate** [wq2012/VoiceIdentityBook#1]
希望作者能给出课后练习编程题的参考答案。

**Comment by wq2012** [comment]
之后会陆续为一些简单的编程题提供示例代码或者开源实现的链接。

不过很大一部分编程题类似于project的性质，锻炼的是读者去网上搜索资料、阅读开源API、动手实践的能力，这部分如果提供了参考答案就失去了练习题的意义。

**Comment by kabrate** [comment]
> 之后会陆续为一些简单的编程题提供示例代码或开源实现的链接。
> 
> 不过很大一部分编程题本身性质，锻炼的是读者去网上搜索资料，阅读开源API，动手实践的能力，这部分如果提供了参考答案就失去了练习题的意义。

hao

**Comment by kabrate** [comment]
> 之后会陆续为一些简单的编程题提供示例代码或者开源实现的链接。
> 
> 不过很大一部分编程题类似于project的性质，锻炼的是读者去网上搜索资料、阅读开源API、动手实践的能力，这部分如果提供了参考答案就失去了练习题的意义。

好的，感谢回复。
