### ISSUE TITLE
if you have millions of speakers,how do you train a voiceprint network?

### ISSUE THREAD

**Issue by campustian** [wq2012/VoiceIdentityBook#2]

**Comment by wq2012** [comment]
超大数据的话，重点在于数据的读取方式和损失函数的设计吧。

损失函数的话用交叉熵肯定不行。可以用triplet loss或[GE2E](https://google.github.io/speaker-id/publications/GE2E/)，就能很好地scale到大数据上。

数据读取方面，要确保每次批的读取包含多个说话人，且每个说话人包含多段语音，这样就能构建有效的正负样本对用于训练。
