### ISSUE TITLE
书中3.5.2数据预处理（p104）中提到的使用语音识别模型来做音频数据的筛选，可有推荐？还有其它语音质量评估工具的建议么？

### ISSUE THREAD

**Issue by PiBingbin** [wq2012/VoiceIdentityBook#5]

**Comment by wq2012** [comment]
任何语音识别模型都可以。你可以去搜索开源ASR模型。甚至条件允许的话你用商业级别的语音识别云服务都可以。

出了ASR之外，也可以用WADA SNR[1]去预估SNR，把SNR太低的去掉。

[1] Chanwoo Kim and Richard M Stern, “Robust signal-to-noise
ratio estimation based on waveform amplitude distribution
analysis,” in Ninth Annual Conference of the International
Speech Communication Association, 2008.

**Comment by PiBingbin** [comment]
> 任何语音识别模型都可以。你可以去搜索开源ASR模型。甚至条件允许的话你用商业级别的语音识别云服务都可以。
> 
> 出了ASR之外，也可以用WADA SNR[1]去预估SNR，把SNR太低的去掉。
> 
> [1] Chanwoo Kim and Richard M Stern, “Robust signal-to-noise
> ratio estimation based on waveform amplitude distribution
> analysis,” in Ninth Annual Conference of the International
> Speech Communication Association, 2008.

非常感谢大佬的解答！
