### ISSUE TITLE
第五章有几个关键词不是很明白：

### ISSUE THREAD

**Issue by 18376672766666** [wq2012/VoiceIdentityBook#7]
第五章有几个关键词不是很明白：
在线聚类和离线聚类
在线聚类和离线聚类的通用接口
Naive聚类方法。
恳请指导，感谢

**Comment by wq2012** [comment]
你的问题太宽泛了，能具体说一下哪里不明白么？

这些概念书中都有清楚的定义。

**Comment by 18376672766666** [comment]
哇，作者亲自回答，太感谢了。
我是有几个地方不太明白：
1：“在线聚类”和“离线聚类”有什么区别？

2：“在线聚类的通用接口”一般有哪些？离线聚类的通用接口是不是类似sklearn.cluster这样子的？

3：书中讲到的“Naive聚类方法”我在网上没有找到相关信息，也不是很明白。能给些参考代码吗

恳请指教

**Comment by wq2012** [comment]
> 1：“在线聚类”和“离线聚类”有什么区别？

区别在于是否需要实时的结果。类比下载电影然后观看，和边下边看的区别。

比如音频中有两个人说话但还没说完，在线聚类需要立即知道现在的聚类结果，尽管这个结果还不完整。离线聚类等两个人说完全部内容之后，一次性给出最终结果。

> 2：“在线聚类的通用接口”一般有哪些？离线聚类的通用接口是不是类似sklearn.cluster这样子的？

`sklearn.cluster`确实是一个离线接口。在线接口书中不是给出代码了吗？我不清楚有哪些开源项目实现了这个接口。在线聚类主要是业界用的比较多，学界大部分时候不太关心实时应用。

> 3：书中讲到的“Naive聚类方法”我在网上没有找到相关信息，也不是很明白。能给些参考代码吗

Naive就是一个最基本的trivial算法，思路非常简单。书中不是给出了算法的详细步骤吗？照着步骤很容易就能明白。
