### ISSUE TITLE
scipy has no attribute of 'single'

### ISSUE THREAD

**Issue by pfeducode** [wq2012/VoiceIdentityBook#8]
第47面的代码，scipy.signal.stft()执行之后报错scipy has no attribute of 'single'

**Comment by wq2012** [comment]
Please try to install the latest version of `scipy`.

If it still did not work, please try this:

```
from scipy import signal

signal.stft(...)
```

**Comment by wq2012** [comment]
Also did you type it correctly?

It is `scipy.signal`, not `scipy.single`.

**Comment by pfeducode** [comment]
from scipy import signal

signal.stft(...)

thank  you! it works well
